### ISSUE TITLE
Question about example.py

### ISSUE THREAD

**Issue by BossaMelon** [tcvrick/Python-Dynamic-Images-for-Action-Recognition#1]
Hello,

in this piece of code in example.py, I think glob.glob doesn't return the right order of the frame, may be sorted(glob.glob) can be used.

```
def main():
    frames = glob.glob('./example_frames/*.jpg')
    frames = [cv2.imread(f) for f in frames]
    dyn_image = get_dynamic_image(frames, normalized=True)
    cv2.imshow('', dyn_image)
    cv2.waitKey()
```

**Comment by tcvrick** [comment]
Hey, thanks for pointing that out. If the frames you are loading are not enumerated with zero-padding (i.e., 001.jpg, 002.jpg, etc.), they won't load in the expected order using the example code.

The issue should be fixed now. https://github.com/tcvrick/Python-Dynamic-Images-for-Action-Recognition/commit/6c56b559280194d2d17007d6d38a4d248c4e0155
